language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: false
    - os: osx

compiler:
  - clang
  - gcc

env:
  - REACTOR_BACKEND=LLVM
  - REACTOR_BACKEND=Subzero

script:
  - $CXX --version
  - mkdir build && cd build
  - cmake -DREACTOR_BACKEND=$REACTOR_BACKEND ..
  - make